cmake_minimum_required(VERSION 3.10)
project(libev C)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

#add_definitions(-DECB_C99=1)
#add_compile_options(-Wall)
set(CMAKE_C_STANDARD 99)
set(CMAKE_CXX_STANDARD 21)


# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/config.h )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev.h )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev++.h )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/event.h )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev.c )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/event.c )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_select.c )
# list(APPEND LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_poll.c )
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR} LIB_DEPENDS)
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_win32.c)
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_kqueue.c)
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_port.c)
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_epoll.c )
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_select.c )
list(REMOVE_ITEM LIB_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/ev_poll.c )


message(WARNING ${LIB_DEPENDS})



add_library(${PROJECT_NAME} STATIC ${LIB_DEPENDS})
set_target_properties(${PROJECT_NAME} PROPERTIES LINKER_LANGUAGE C)
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})